version: "3.7"

services:
 frontend:
  image: node:lts-slim
  # command: npm run dev
  command: bash -c "
    npm install
    && npm run dev"
  volumes:
    - .:/usr/src/app
  working_dir: /usr/src/app
  ports:
    - "3000:3000"
  environment:
    HOST: 0.0.0.0
